// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: SophonPatch.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct SophonPatchProto: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var patchAssets: [SophonPatchAssetProperty] = []

  var unusedAssets: [SophonUnusedAssetProperty] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SophonPatchAssetProperty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var assetName: String = String()

  var assetSize: Int64 = 0

  var assetHashMd5: String = String()

  var assetInfos: [SophonPatchAssetInfo] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SophonPatchAssetInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var versionTag: String = String()

  var chunk: SophonPatchAssetChunk {
    get {_chunk ?? SophonPatchAssetChunk()}
    set {_chunk = newValue}
  }
  /// Returns true if `chunk` has been explicitly set.
  var hasChunk: Bool {self._chunk != nil}
  /// Clears the value of `chunk`. Subsequent reads from it will return its default value.
  mutating func clearChunk() {self._chunk = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _chunk: SophonPatchAssetChunk? = nil
}

nonisolated struct SophonPatchAssetChunk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var patchName: String = String()

  var versionTag: String = String()

  var buildID: String = String()

  var patchSize: Int64 = 0

  var patchMd5: String = String()

  var patchOffset: Int64 = 0

  var patchLength: Int64 = 0

  var originalFileName: String = String()

  var originalFileLength: Int64 = 0

  var originalFileMd5: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SophonUnusedAssetProperty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var versionTag: String = String()

  var assetInfos: [SophonUnusedAssetInfo] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SophonUnusedAssetInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var assets: [SophonUnusedAssetFile] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SophonUnusedAssetFile: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var fileName: String = String()

  var fileSize: Int64 = 0

  var fileMd5: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension SophonPatchProto: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonPatchProto"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}PatchAssets\0\u{1}UnusedAssets\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.patchAssets) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.unusedAssets) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.patchAssets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.patchAssets, fieldNumber: 1)
    }
    if !self.unusedAssets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.unusedAssets, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonPatchProto, rhs: SophonPatchProto) -> Bool {
    if lhs.patchAssets != rhs.patchAssets {return false}
    if lhs.unusedAssets != rhs.unusedAssets {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SophonPatchAssetProperty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonPatchAssetProperty"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}AssetName\0\u{1}AssetSize\0\u{1}AssetHashMd5\0\u{1}AssetInfos\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.assetName) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.assetSize) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.assetHashMd5) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.assetInfos) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.assetName.isEmpty {
      try visitor.visitSingularStringField(value: self.assetName, fieldNumber: 1)
    }
    if self.assetSize != 0 {
      try visitor.visitSingularInt64Field(value: self.assetSize, fieldNumber: 2)
    }
    if !self.assetHashMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.assetHashMd5, fieldNumber: 3)
    }
    if !self.assetInfos.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.assetInfos, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonPatchAssetProperty, rhs: SophonPatchAssetProperty) -> Bool {
    if lhs.assetName != rhs.assetName {return false}
    if lhs.assetSize != rhs.assetSize {return false}
    if lhs.assetHashMd5 != rhs.assetHashMd5 {return false}
    if lhs.assetInfos != rhs.assetInfos {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SophonPatchAssetInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonPatchAssetInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}VersionTag\0\u{1}Chunk\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.versionTag) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._chunk) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.versionTag.isEmpty {
      try visitor.visitSingularStringField(value: self.versionTag, fieldNumber: 1)
    }
    try { if let v = self._chunk {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonPatchAssetInfo, rhs: SophonPatchAssetInfo) -> Bool {
    if lhs.versionTag != rhs.versionTag {return false}
    if lhs._chunk != rhs._chunk {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SophonPatchAssetChunk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonPatchAssetChunk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}PatchName\0\u{1}VersionTag\0\u{1}BuildId\0\u{1}PatchSize\0\u{1}PatchMd5\0\u{1}PatchOffset\0\u{1}PatchLength\0\u{1}OriginalFileName\0\u{1}OriginalFileLength\0\u{1}OriginalFileMd5\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.patchName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.versionTag) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.buildID) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.patchSize) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.patchMd5) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.patchOffset) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.patchLength) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.originalFileName) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.originalFileLength) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.originalFileMd5) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.patchName.isEmpty {
      try visitor.visitSingularStringField(value: self.patchName, fieldNumber: 1)
    }
    if !self.versionTag.isEmpty {
      try visitor.visitSingularStringField(value: self.versionTag, fieldNumber: 2)
    }
    if !self.buildID.isEmpty {
      try visitor.visitSingularStringField(value: self.buildID, fieldNumber: 3)
    }
    if self.patchSize != 0 {
      try visitor.visitSingularInt64Field(value: self.patchSize, fieldNumber: 4)
    }
    if !self.patchMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.patchMd5, fieldNumber: 5)
    }
    if self.patchOffset != 0 {
      try visitor.visitSingularInt64Field(value: self.patchOffset, fieldNumber: 6)
    }
    if self.patchLength != 0 {
      try visitor.visitSingularInt64Field(value: self.patchLength, fieldNumber: 7)
    }
    if !self.originalFileName.isEmpty {
      try visitor.visitSingularStringField(value: self.originalFileName, fieldNumber: 8)
    }
    if self.originalFileLength != 0 {
      try visitor.visitSingularInt64Field(value: self.originalFileLength, fieldNumber: 9)
    }
    if !self.originalFileMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.originalFileMd5, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonPatchAssetChunk, rhs: SophonPatchAssetChunk) -> Bool {
    if lhs.patchName != rhs.patchName {return false}
    if lhs.versionTag != rhs.versionTag {return false}
    if lhs.buildID != rhs.buildID {return false}
    if lhs.patchSize != rhs.patchSize {return false}
    if lhs.patchMd5 != rhs.patchMd5 {return false}
    if lhs.patchOffset != rhs.patchOffset {return false}
    if lhs.patchLength != rhs.patchLength {return false}
    if lhs.originalFileName != rhs.originalFileName {return false}
    if lhs.originalFileLength != rhs.originalFileLength {return false}
    if lhs.originalFileMd5 != rhs.originalFileMd5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SophonUnusedAssetProperty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonUnusedAssetProperty"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}VersionTag\0\u{1}AssetInfos\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.versionTag) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.assetInfos) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.versionTag.isEmpty {
      try visitor.visitSingularStringField(value: self.versionTag, fieldNumber: 1)
    }
    if !self.assetInfos.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.assetInfos, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonUnusedAssetProperty, rhs: SophonUnusedAssetProperty) -> Bool {
    if lhs.versionTag != rhs.versionTag {return false}
    if lhs.assetInfos != rhs.assetInfos {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SophonUnusedAssetInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonUnusedAssetInfo"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}Assets\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.assets) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.assets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.assets, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonUnusedAssetInfo, rhs: SophonUnusedAssetInfo) -> Bool {
    if lhs.assets != rhs.assets {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SophonUnusedAssetFile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonUnusedAssetFile"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}FileName\0\u{1}FileSize\0\u{1}FileMd5\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.fileName) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.fileSize) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.fileMd5) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.fileName.isEmpty {
      try visitor.visitSingularStringField(value: self.fileName, fieldNumber: 1)
    }
    if self.fileSize != 0 {
      try visitor.visitSingularInt64Field(value: self.fileSize, fieldNumber: 2)
    }
    if !self.fileMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.fileMd5, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonUnusedAssetFile, rhs: SophonUnusedAssetFile) -> Bool {
    if lhs.fileName != rhs.fileName {return false}
    if lhs.fileSize != rhs.fileSize {return false}
    if lhs.fileMd5 != rhs.fileMd5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
