// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: SophonManifest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

nonisolated struct SophonManifestProto: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var assets: [SophonManifestAssetProperty] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SophonManifestAssetProperty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var assetName: String = String()

  var assetChunks: [SophonManifestAssetChunk] = []

  var assetType: Int32 = 0

  var assetSize: Int64 = 0

  var assetHashMd5: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SophonManifestAssetChunk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var chunkName: String = String()

  var chunkDecompressedHashMd5: String = String()

  var chunkOnFileOffset: Int64 = 0

  var chunkSize: Int64 = 0

  var chunkSizeDecompressed: Int64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

nonisolated extension SophonManifestProto: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonManifestProto"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}Assets\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.assets) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.assets.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.assets, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonManifestProto, rhs: SophonManifestProto) -> Bool {
    if lhs.assets != rhs.assets {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SophonManifestAssetProperty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonManifestAssetProperty"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}AssetName\0\u{1}AssetChunks\0\u{1}AssetType\0\u{1}AssetSize\0\u{1}AssetHashMd5\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.assetName) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.assetChunks) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.assetType) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.assetSize) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.assetHashMd5) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.assetName.isEmpty {
      try visitor.visitSingularStringField(value: self.assetName, fieldNumber: 1)
    }
    if !self.assetChunks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.assetChunks, fieldNumber: 2)
    }
    if self.assetType != 0 {
      try visitor.visitSingularInt32Field(value: self.assetType, fieldNumber: 3)
    }
    if self.assetSize != 0 {
      try visitor.visitSingularInt64Field(value: self.assetSize, fieldNumber: 4)
    }
    if !self.assetHashMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.assetHashMd5, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonManifestAssetProperty, rhs: SophonManifestAssetProperty) -> Bool {
    if lhs.assetName != rhs.assetName {return false}
    if lhs.assetChunks != rhs.assetChunks {return false}
    if lhs.assetType != rhs.assetType {return false}
    if lhs.assetSize != rhs.assetSize {return false}
    if lhs.assetHashMd5 != rhs.assetHashMd5 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SophonManifestAssetChunk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = "SophonManifestAssetChunk"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ChunkName\0\u{1}ChunkDecompressedHashMd5\0\u{1}ChunkOnFileOffset\0\u{1}ChunkSize\0\u{1}ChunkSizeDecompressed\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.chunkName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.chunkDecompressedHashMd5) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.chunkOnFileOffset) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.chunkSize) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.chunkSizeDecompressed) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chunkName.isEmpty {
      try visitor.visitSingularStringField(value: self.chunkName, fieldNumber: 1)
    }
    if !self.chunkDecompressedHashMd5.isEmpty {
      try visitor.visitSingularStringField(value: self.chunkDecompressedHashMd5, fieldNumber: 2)
    }
    if self.chunkOnFileOffset != 0 {
      try visitor.visitSingularInt64Field(value: self.chunkOnFileOffset, fieldNumber: 3)
    }
    if self.chunkSize != 0 {
      try visitor.visitSingularInt64Field(value: self.chunkSize, fieldNumber: 4)
    }
    if self.chunkSizeDecompressed != 0 {
      try visitor.visitSingularInt64Field(value: self.chunkSizeDecompressed, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SophonManifestAssetChunk, rhs: SophonManifestAssetChunk) -> Bool {
    if lhs.chunkName != rhs.chunkName {return false}
    if lhs.chunkDecompressedHashMd5 != rhs.chunkDecompressedHashMd5 {return false}
    if lhs.chunkOnFileOffset != rhs.chunkOnFileOffset {return false}
    if lhs.chunkSize != rhs.chunkSize {return false}
    if lhs.chunkSizeDecompressed != rhs.chunkSizeDecompressed {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
